# Generated by Django 3.0.5 on 2020-04-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='putdata',
            new_name='putdate',
        ),
    ]
